logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      "()": src.domain.logger.formatter.DefaultFormatter
  handlers:
    console:
      level: INFO
      formatter: default
      class: logging.StreamHandler
      stream: ext://sys.stdout
  root:
    handlers: [console]
    level: DEBUG

app:
  timeout_seconds: 20
  port: 5000
  host: 0.0.0.0
